CREATE USER IF NOT EXISTS 'culturAdvisor'@'localhost' IDENTIFIED BY 'culturAdvisor';

DROP DATABASE IF EXISTS cultur_advisor;
CREATE DATABASE cultur_advisor;

GRANT SELECT, INSERT, UPDATE, DELETE ON cultur_advisor.* TO 'culturAdvisor'@'localhost';

FLUSH privileges;

USE cultur_advisor;

CREATE table items
(
    origine TEXT,
    titre TEXT,
    description TEXT,
    site_internet TEXT,
    identifiant TEXT,
    code_postal TEXT,
    geolocalisation TEXT,
    adresse TEXT,
    commune TEXT,
    domaine TEXT,
    organisme TEXT,
    public_cible TEXT,
    temps_activite TEXT,
    rattachement_organisme TEXT,
    types_ressource TEXT,
    activite TEXT,
    perenite_ressource TEXT,
    niveau_scolaire_enfant TEXT,
    contenue_adapte TEXT,
    adresse_mail TEXT,
    couverture_geographique TEXT,
    type_de_producteur TEXT,
    direction TEXT,
    mots_cles TEXT,
    formats TEXT,
    frequence_de_mise_a_jour TEXT,
    volumetrie TEXT,
    statut_ouverture TEXT,
    date_de_mise_a_jour TEXT,
    actif_inactif TEXT,
    sous_domaine TEXT,
    service TEXT,
    sous_direction_departement TEXT,
    precision_domaine TEXT,
    donnees_geolocalise TEXT,
    adresse_postale TEXT,
    region TEXT,
    departement TEXT,
    code_insee TEXT,
    code_insee_EPCI TEXT,
    libelle_EPCI TEXT,
    periode_principale TEXT,
    numero_de_voie TEXT,
    type_de_voie TEXT,
    nom_de_voie TEXT,
    complement_adresse TEXT,
    discipline_dominante TEXT,
    sous_categorie_cinema TEXT,
    decenie_de_creation TEXT,
    annee_de_creation TEXT,
    sous_categorie_musique TEXT,
    sous_categorie_musique_CNM TEXT,
    sous_categorie_livre TEXT,
    sous_categorie_spectacle TEXT,
    identifiant_CNM TEXT,
    identifiant_agence_A TEXT,
    sous_categorie_art_visuel TEXT,
    type_equipement_lieux TEXT,
    label TEXT,
    adresse_postal TEXT,
    sources TEXT,
    identifiant_origine TEXT,
    num_departement TEXT,
    num_region TEXT,
    fonctions TEXT,
    rang TEXT,
    identifiant_deps TEXT,
    precision_equipement TEXT,
    nb_salles_theatre TEXT,
    jauge_theatre TEXT,
    surface_bibliotheque TEXT,
    multiplexe TEXT,
    type_cinema TEXT,
    nb_fauteils_cinema TEXT,
    nb_ecrans TEXT,
    keyword TEXT,
    license TEXT,
    license_url TEXT,
    langage TEXT,
    modifie TEXT,
    publie TEXT,
    records_count TEXT,
    attributions TEXT,
    domain TEXT,
    staged TEXT,
    visibility TEXT,
    referencs TEXT
);
